### ISSUE TITLE
`ope:damage` entity action not working

### ISSUE THREAD

**Issue by mosharky** [NotJustOrigins/origins-power-expansion#1]
I've been attempting to use `ope:damage` to repair tools, but I can't get it to work at all. I just get this error in the log: `There was a problem reading power file grounded_origins:banished_piglin/mending (skipping): null`

I'm on the Forge version. Am I doing something wrong here? The power works once I remove the entity_action
```json
{
    "name": "Mending",
    "description": "Mending",
    "type": "origins:action_over_time",
    "interval": 1,
    "entity_action": {
        "type": "ope:damage",
        "amount": -10
    },
    "condition": {
        "type": "origins:equipped_item",
        "equipment_slot": "mainhand",
        "item_condition": {
            "type": "origins:ingredient",
            "ingredient": {
                "tag": "grounded_origins:tools/golden"
            }
        }
    }
}
```
I've also tried getting a hold of you on the Origins discord like the wiki suggests, but it seems that you left it. You also put the wrong discord link in the wiki.

**Comment by Jarva** [comment]
`ope:damage` is an item action not an entity action, the example in the wiki is wrong. This library is no longer being developed but the features should work as is. The discord link was correct at the time, I'll see if I can get the wiki updated.

**Comment by mosharky** [comment]
Ah okay, thank you! Are you able check out the modify enchant documentation too? I’m not sure if I got it wrong or if the documentation isn’t accurate.

 Thanks again mate, I really appreciate you coming back for this

**Comment by Jarva** [comment]
`ope:modify_enchantment_level` seems to have correct documentation, can you show your power.

**Comment by mosharky** [comment]
Will have to do tomorrow since in my bed, though I think I misunderstood it’s purpose. Does it quite literally “modify” an existing enchantment on a tool, or does it add the enchantment to a tool?

**Comment by Jarva** [comment]
It modifies the effective enchant level a player has active. If you use the example on the wiki, any bow picked up would act like it has infinity, but would not show as enchanted because the power is on the player.

**Comment by mosharky** [comment]
Ah I've got it working now. You know if there's a way to only make it apply to a specific equipment slot?

Edit: Unbreaking doesn't seem to work with it: 
```json
{
    "type": "ope:modify_enchantment_level",
    "enchantment": "unbreaking",
    "modifier": {
      "operation": "addition",
      "value": 3
    }
}

**Comment by mosharky** [comment]
Oh, huh. I couldn't just do /reload for this power, I restarted my game and it works now

Edit: The entire power is loaded on start-up or something. I added conditions, but they'd check if the player meets the conditions just once after loading up my world.

Thanks again for all the help dude! I suppose I'll wait for the day you come back to the modding community. Hopefully that day comes soon!
